In [3]:
import pandas as pd

In [4]:
excel_file = "../data/EduPro Online Platform.xlsx"

In [5]:
users = pd.read_excel(
    excel_file,
    sheet_name="Users"
)

In [6]:
users.head()

   UserID        UserName  Age  Gender                             Email
0  U00001    wilsonjordan   15    Male            patricia27@hotmail.com
1  U00002        angela22   29  Female             hallrandy@hotmail.com
2  U00003  morrisonamanda   33  Female               ganderson@yahoo.com
3  U00004       fthornton   23  Female  christensencatherine@outlook.com
4  U00005  fostergeoffrey   21    Male            karenfuentes@yahoo.com

In [7]:
courses = pd.read_excel(
    excel_file,
    sheet_name="Courses"
)

courses.head()

,CourseID,CourseName,CourseCategory,CourseType,CourseLevel,CoursePrice,CourseDuration,CourseRating
0,CR00001,Python Basics,Programming,Paid,Beginner,472.28,11.00,4.74
1,CR00002,Java Programming,Programming,Free,Intermediate,0.00,37.70,2.43
2,CR00003,C++ for Beginners,Programming,Free,Beginner,0.00,19.53,3.85
3,CR00004,Advanced Python,Programming,Free,Beginner,0.00,45.13,2.88
4,CR00005,Full Stack Development,Programming,Free,Beginner,0.00,28.68,1.28

In [8]:
transactions = pd.read_excel(
    excel_file,
    sheet_name="Transactions"
)

transactions.head()

,TransactionID,UserID,CourseID,TransactionDate,Amount,PaymentMethod,TeacherID
0,TT00001,U00003,CR00016,2025-10-25,0.0,PayPal,TC00040
1,TT00002,U00003,CR00037,2025-01-13,0.0,PayPal,TC00040
2,TT00003,U00003,CR00019,2025-03-28,0.0,Bank Transfer,TC00040
3,TT00004,U00004,CR00048,2025-06-02,0.0,Bank Transfer,TC00040
4,TT00005,U00004,CR00060,2025-08-10,0.0,PayPal,TC00042

In [9]:
teachers = pd.read_excel(
    excel_file,
    sheet_name="Teachers"
)

teachers.head()

,TeacherID,TeacherName,Age,Gender,Expertise,YearsOfExperience,TeacherRating
0,TC00001,Leonard Montgomery,44,Female,Cybersecurity,6,3.24
1,TC00002,Jill Day,32,Female,Digital Marketing,9,4.14
2,TC00003,Amber Torres,32,Male,Design,4,1.56
3,TC00004,Kristi Scott,34,Female,Machine Learning,9,4.39
4,TC00005,David Williams,34,Male,Finance,2,3.11

In [10]:
print(users.columns)

Index(['UserID', 'UserName', 'Age', 'Gender', 'Email'], dtype='str')

In [11]:
print(courses.columns)

Index(['CourseID', 'CourseName', 'CourseCategory', 'CourseType', 'CourseLevel',
       'CoursePrice', 'CourseDuration', 'CourseRating'],
      dtype='str')

In [12]:
print(transactions.columns)

Index(['TransactionID', 'UserID', 'CourseID', 'TransactionDate', 'Amount',
       'PaymentMethod', 'TeacherID'],
      dtype='str')

In [13]:
print(teachers.columns)

Index(['TeacherID', 'TeacherName', 'Age', 'Gender', 'Expertise',
       'YearsOfExperience', 'TeacherRating'],
      dtype='str')

In [14]:
print(users.shape)
print(courses.shape)
print(transactions.shape)
print(teachers.shape)

(3000, 5)
(60, 8)
(10000, 7)
(60, 7)

In [15]:
users.isnull().sum()

UserID      0
UserName    0
Age         0
Gender      0
Email       0
dtype: int64

In [16]:
courses.isnull().sum()

CourseID          0
CourseName        0
CourseCategory    0
CourseType        0
CourseLevel       0
CoursePrice       0
CourseDuration    0
CourseRating      0
dtype: int64

In [17]:
transactions.isnull().sum()

TransactionID      0
UserID             0
CourseID           0
TransactionDate    0
Amount             0
PaymentMethod      0
TeacherID          0
dtype: int64

In [18]:
teachers.isnull().sum()

TeacherID            0
TeacherName          0
Age                  0
Gender               0
Expertise            0
YearsOfExperience    0
TeacherRating        0
dtype: int64

In [19]:
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   UserID    3000 non-null   str
 1   UserName  3000 non-null   str
 2   Age       3000 non-null   int64
 3   Gender    3000 non-null   str
 4   Email     3000 non-null   str
dtypes: int64(1), str(4)
memory usage: 239.5 KB

In [20]:
courses.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CourseID        60 non-null     str
 1   CourseName      60 non-null     str
 2   CourseCategory  60 non-null     str
 3   CourseType      60 non-null     str
 4   CourseLevel     60 non-null     str
 5   CoursePrice     60 non-null     float64
 6   CourseDuration  60 non-null     float64
 7   CourseRating    60 non-null     float64
dtypes: float64(3), str(5)
memory usage: 6.9 KB

In [21]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10000 non-null  str
 1   UserID           10000 non-null  str
 2   CourseID         10000 non-null  str
 3   TransactionDate  10000 non-null  datetime64[us]
 4   Amount           10000 non-null  float64
 5   PaymentMethod    10000 non-null  str
 6   TeacherID        10000 non-null  str
dtypes: datetime64[us](1), float64(1), str(5)
memory usage: 908.0 KB

In [22]:
teachers.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   TeacherID          60 non-null     str
 1   TeacherName        60 non-null     str
 2   Age                60 non-null     int64
 3   Gender             60 non-null     str
 4   Expertise          60 non-null     str
 5   YearsOfExperience  60 non-null     int64
 6   TeacherRating      60 non-null     float64
dtypes: float64(1), int64(2), str(4)
memory usage: 5.7 KB

# Dataset Understanding

## Users Dataset

Rows: 3000

Columns:
- UserID
- Age
- Gender

## Courses Dataset

Rows: 60

Columns:
- CourseID
- Category
- Level
- Rating

## Transactions Dataset

Rows: 10000

Columns:
- UserID
- CourseID
- Amount
- TransactionDate

## Teachers Dataset

Rows: 60

Columns:
- TeacherID
- TeacherName

In [23]:
print(users.columns)
print(courses.columns)
print(transactions.columns)
print(teachers.columns)

Index(['UserID', 'UserName', 'Age', 'Gender', 'Email'], dtype='str')
Index(['CourseID', 'CourseName', 'CourseCategory', 'CourseType', 'CourseLevel',
       'CoursePrice', 'CourseDuration', 'CourseRating'],
      dtype='str')
Index(['TransactionID', 'UserID', 'CourseID', 'TransactionDate', 'Amount',
       'PaymentMethod', 'TeacherID'],
      dtype='str')
Index(['TeacherID', 'TeacherName', 'Age', 'Gender', 'Expertise',
       'YearsOfExperience', 'TeacherRating'],
      dtype='str')