In [1]:
import pandas as pd
import numpy as np

In [2]:
excel_file = "../data/EduPro Online Platform.xlsx"

In [3]:
users = pd.read_excel(excel_file,sheet_name="Users")

courses = pd.read_excel(excel_file,sheet_name="Courses")

transactions = pd.read_excel(excel_file,sheet_name="Transactions")

teachers = pd.read_excel(excel_file,sheet_name="Teachers")

In [4]:
master = transactions.merge(
    courses,
    on="CourseID",
    how="left"
)

In [5]:
master.head()

,TransactionID,UserID,CourseID,TransactionDate,Amount,PaymentMethod,TeacherID,CourseName,CourseCategory,CourseType,CourseLevel,CoursePrice,CourseDuration,CourseRating
0,TT00001,U00003,CR00016,2025-10-25,0.0,PayPal,TC00040,Digital Marketing,Marketing,Free,Intermediate,0.0,42.68,4.72
1,TT00002,U00003,CR00037,2025-01-13,0.0,PayPal,TC00040,Scrum Essentials,Project Management,Free,Intermediate,0.0,33.93,3.45
2,TT00003,U00003,CR00019,2025-03-28,0.0,Bank Transfer,TC00040,Content Marketing,Marketing,Free,Advanced,0.0,18.00,2.98
3,TT00004,U00004,CR00048,2025-06-02,0.0,Bank Transfer,TC00040,AI Ethics,Artificial Intelligence,Free,Beginner,0.0,42.70,3.64
4,TT00005,U00004,CR00060,2025-08-10,0.0,PayPal,TC00042,Content Creation,Digital Marketing,Free,Beginner,0.0,8.95,2.14

In [6]:
master = master.merge(
    users,
    on="UserID",
    how="left"
)

In [7]:
master.head()

,TransactionID,UserID,CourseID,TransactionDate,Amount,PaymentMethod,TeacherID,CourseName,CourseCategory,CourseType,CourseLevel,CoursePrice,CourseDuration,CourseRating,UserName,Age,Gender,Email
0,TT00001,U00003,CR00016,2025-10-25,0.0,PayPal,TC00040,Digital Marketing,Marketing,Free,Intermediate,0.0,42.68,4.72,morrisonamanda,33,Female,ganderson@yahoo.com
1,TT00002,U00003,CR00037,2025-01-13,0.0,PayPal,TC00040,Scrum Essentials,Project Management,Free,Intermediate,0.0,33.93,3.45,morrisonamanda,33,Female,ganderson@yahoo.com
2,TT00003,U00003,CR00019,2025-03-28,0.0,Bank Transfer,TC00040,Content Marketing,Marketing,Free,Advanced,0.0,18.00,2.98,morrisonamanda,33,Female,ganderson@yahoo.com
3,TT00004,U00004,CR00048,2025-06-02,0.0,Bank Transfer,TC00040,AI Ethics,Artificial Intelligence,Free,Beginner,0.0,42.70,3.64,fthornton,23,Female,christensencatherine@outlook.com
4,TT00005,U00004,CR00060,2025-08-10,0.0,PayPal,TC00042,Content Creation,Digital Marketing,Free,Beginner,0.0,8.95,2.14,fthornton,23,Female,christensencatherine@outlook.com

In [8]:
master.shape

(10000, 18)

In [9]:
total_courses = master.groupby(
    "UserID"
)["CourseID"].count()

In [10]:
total_courses.head()

UserID
U00001     1
U00002     1
U00003    11
U00004    13
U00005     2
Name: CourseID, dtype: int64

In [11]:
total_spending = master.groupby(
    "UserID"
)["Amount"].sum()

In [12]:
total_spending.head()

UserID
U00001    394.26
U00002      0.00
U00003    613.98
U00004    982.05
U00005    346.71
Name: Amount, dtype: float64

In [13]:
category_diversity = master.groupby(
    "UserID"
)["CourseCategory"].nunique()

In [14]:
category_diversity.head()

UserID
U00001    1
U00002    1
U00003    7
U00004    8
U00005    2
Name: CourseCategory, dtype: int64

In [15]:
avg_rating = master.groupby(
    "UserID"
)["CourseRating"].mean()

In [16]:
avg_rating.head()

UserID
U00001    1.350000
U00002    2.880000
U00003    2.889091
U00004    3.451538
U00005    2.055000
Name: CourseRating, dtype: float64

In [17]:
preferred_category = (
    master.groupby("UserID")
    ["CourseCategory"]
    .agg(lambda x: x.mode()[0])
)

In [18]:
preferred_level = (
    master.groupby("UserID")
    ["CourseLevel"]
    .agg(lambda x: x.mode()[0])
)

In [19]:
learner_profile = pd.DataFrame({
    "TotalCourses": total_courses,
    "TotalSpending": total_spending,
    "CategoryDiversity": category_diversity,
    "AvgRating": avg_rating,
    "PreferredCategory": preferred_category,
    "PreferredLevel": preferred_level
})

In [20]:
learner_profile.head()

,TotalCourses,TotalSpending,CategoryDiversity,AvgRating,PreferredCategory,PreferredLevel
UserID,,,,,,
U00001,1,394.26,1,1.350000,Cybersecurity,Intermediate
U00002,1,0.00,1,2.880000,Programming,Beginner
U00003,11,613.98,7,2.889091,Marketing,Advanced
U00004,13,982.05,8,3.451538,Digital Marketing,Intermediate
U00005,2,346.71,2,2.055000,Programming,Advanced

In [21]:
learner_profile.to_csv(
    "../outputs/learner_profile.csv"
)